require('dotenv').config();
const { Pool } = require('pg');

const pool = new Pool({
  connectionString: process.env.DATABASE_URL
});

const mediumParagraphs = [
  "When we engage in genuine dialogue, we open ourselves up to new perspectives that challenge our preconceptions. True communication is not about winning an argument, but about expanding our understanding of the human experience. By actively listening and asking thoughtful questions, we create a safe space for others to share their vulnerabilities without fear of judgment.",
  "Mastering the art of storytelling allows you to translate complex emotions into relatable experiences. A well-told narrative can capture the imagination, bridging the gap between strangers and fostering profound empathy. It requires a delicate balance of pacing, descriptive language, and an intuitive sense of what will resonate most deeply with your audience.",
  "During an interview or formal discussion, your tone and pacing carry as much weight as your actual words. Taking a moment to breathe and center yourself before speaking projects quiet confidence and professional authority. Furthermore, adjusting your volume to match the gravity of the topic ensures that your message is received exactly as intended.",
  "Our daily interactions may seem routine, but they form the invisible fabric of our social lives. Approaching everyday conversations with kindness and presence can transform a mundane exchange into a moment of genuine connection. Recognizing the value in these small, seemingly insignificant encounters often leads to a more fulfilling and grounded sense of community.",
  "Expressing difficult emotions requires both courage and a precise vocabulary. When we accurately articulate how we feel, we give others the opportunity to support us effectively, turning personal struggle into shared strength. This process not only accelerates our own healing but also deepens the trust and intimacy within our most important relationships.",
  "The ability to remain calm and articulate under pressure is a hallmark of emotional maturity. When conflicts arise, responding with measured, empathetic words can de-escalate the situation and pave the way for meaningful resolution. It demands a high level of self-awareness to pause your initial reaction and choose a constructive path forward.",
  "Active listening is a dynamic process that involves fully concentrating on what is being said rather than passively hearing the message. It is the fundamental building block of any successful personal or professional relationship. Providing verbal and non-verbal feedback demonstrates that you genuinely value the speaker's time, insights, and underlying emotions.",
  "Finding your authentic voice takes time, patience, and a willingness to engage in deep self-reflection. As you grow more comfortable with your own communication style, you will discover that people are naturally drawn to sincerity and unwavering honesty. It is an ongoing journey of discovering who you are and learning how to express that truth without apology.",
  "A compelling narrative doesn't just relay facts; it weaves them together in a way that resonates emotionally with the audience. Cultivating this skill empowers you to advocate for yourself and inspire those around you to take meaningful action. Whether in a boardroom or at a dinner table, a well-structured story is the most effective tool for lasting persuasion.",
  "The rapid integration of artificial intelligence into enterprise operations demands a fundamental shift in how we approach problem-solving. Organizations that proactively adapt their strategies will maintain a crucial competitive advantage in the modern economy. Employees must be trained to collaborate alongside these algorithms, utilizing their unprecedented data-processing capabilities to drive innovation.",
  "Navigating geopolitical tensions requires a nuanced understanding of historical grievances and current economic dependencies. Diplomats must meticulously choose their words to de-escalate conflicts while firmly protecting their national interests. A single misinterpretation of intent can rapidly unravel months of delicate negotiations, underscoring the absolute necessity for precision in international discourse.",
  "In the realm of academic research, the peer review process serves as a vital safeguard for maintaining factual accuracy. Scholars depend on constructive criticism to refine their hypotheses and contribute meaningful discoveries to their respective fields. By subjecting empirical data to rigorous, independent scrutiny, the scientific community collectively ensures the integrity of its expanding knowledge base.",
  "Modern journalism faces the unprecedented challenge of combating misinformation in real time across decentralized digital platforms. Responsible reporting demands rigorous fact-checking and an unwavering commitment to presenting objective truth to the public. Journalists must consistently prioritize verified sources over sensationalized rumors to maintain the vital trust of an increasingly skeptical audience.",
  "Corporate leadership is increasingly focused on environmental, social, and governance criteria as a primary driver of valuation. Investors recognize that companies demonstrating ethical practices and sustainable operations are better positioned for long-term financial stability. Implementing these rigorous standards not only mitigates regulatory risks but also attracts top-tier talent seeking purposeful employment.",
  "The language of formal negotiation is inherently strategic, often relying on subtle implications rather than blunt demands. Mastering this sophisticated communication style is essential for finalizing complex international agreements. Negotiators must expertly read the room, balancing aggressive tactical maneuvering with a genuine willingness to seek mutually beneficial compromises."
];

const hardParagraphs = [
  "The intricacies of human psychology dictate that our most profound personal breakthroughs often emerge from periods of intense vulnerability and emotional uncertainty, challenging us to reevaluate our core identity. When individuals are forced to confront their deeply ingrained defense mechanisms, they often discover an untapped reservoir of resilience that fundamentally alters their worldview. Furthermore, the capacity to articulate these internal paradigm shifts requires an extraordinarily sophisticated emotional vocabulary. Only by meticulously deconstructing our past traumas can we begin to construct a more authentic and purposeful framework for our future interpersonal relationships.",
  "During high-stakes professional interviews, the candidate who successfully balances authentic self-representation with strategic corporate alignment consistently outperforms those who rely solely on rehearsed, formulaic responses. Evaluators at the executive level are trained to detect nuanced micro-expressions that betray cognitive dissonance or a lack of genuine conviction. Consequently, mastering this high-pressure environment demands rigorous psychological preparation and an unwavering commitment to transparent communication. The ultimate goal is to seamlessly weave your unique professional narrative into the broader, overarching vision of the organization you are seeking to join.",
  "Storytelling transcends mere entertainment; it is an evolutionary survival mechanism that enables communities to encode complex moral lessons, preserve generational wisdom, and foster cohesive social architectures. Throughout human history, tribes that developed sophisticated oral traditions were demonstrably more successful at navigating environmental catastrophes and coordinating large-scale collective action. Today, this ancient biological imperative manifests in our insatiable appetite for cinema, literature, and digital media. Understanding the structural mechanics of these archetypal narratives is essential for anyone attempting to capture the fragmented attention of the modern public.",
  "Mastering the subtleties of interpersonal communication requires an acute awareness of non-verbal cues, microscopic shifts in tone, and the underlying contextual dynamics that govern every human interaction. Frequently, the most critical information in a dialogue is not explicitly stated, but rather conveyed through deliberate silences, subtle hesitations, and fleeting facial expressions. Developing the emotional intelligence required to accurately decipher these covert signals is a lifelong endeavor that yields immeasurable dividends in both our private lives and professional careers. Ultimately, it is the unspoken subtext that dictates the true trajectory of our most significant negotiations.",
  "When we actively dismantle the cognitive dissonance separating our private emotional state from our outward expressions, we cultivate a profound sense of inner peace and relational authenticity. This rigorous introspective process requires us to critically examine the societal conditioning that encourages us to suppress our most authentic, albeit inconvenient, emotional reactions. By systematically rejecting these superficial behavioral paradigms, we invite a level of psychological vulnerability that is inherently terrifying yet absolutely necessary for genuine human connection. The courage required to live transparently is perhaps the rarest and most admirable of all modern virtues.",
  "The daily routines we establish may seem insignificant in isolation, but compounded over decades, they dictate the ultimate trajectory of our professional achievements and the depth of our personal fulfillment. Neuroscientific research consistently demonstrates that habitual behaviors literally rewire the synaptic pathways of the brain, making proactive, disciplined choices increasingly automated over time. Conversely, allowing negative communication patterns to take root guarantees a gradual erosion of trust and mutual respect within our closest relationships. Therefore, cultivating a deliberate and mindful approach to our daily interactions is the most pragmatic strategy for ensuring long-term emotional well-being.",
  "Articulating complex emotional states with precise vocabulary not only accelerates psychological healing but also provides our support networks with the clarity required to offer meaningful, targeted assistance. Unfortunately, the modern vernacular frequently relies on vague, generalized descriptors that fail to capture the nuanced realities of the human condition, leaving individuals feeling fundamentally misunderstood. By expanding our emotional lexicon, we empower ourselves to navigate the labyrinthine complexities of grief, joy, and existential anxiety with unprecedented grace. This linguistic precision acts as a crucial bridge, allowing empathy to traverse the otherwise insurmountable gulf between isolated subjective experiences.",
  "Navigating ideological disagreements gracefully demands that we temporarily suspend our deeply ingrained defensive reflexes in favor of genuine intellectual curiosity and empathetic active listening. In an era characterized by hyper-partisan polarization, the willingness to entertain conflicting viewpoints without immediately resorting to ad hominem attacks is an increasingly scarce commodity. True intellectual courage involves systematically interrogating the foundational premises of our own arguments while actively seeking the strongest possible interpretation of our opponent's position. This methodology, often referred to as steel-manning, is the only reliable mechanism for breaking through the echo chambers that currently paralyze constructive public discourse.",
  "The modern narrative arc, whether deployed in corporate branding or personal memoirs, relies heavily on establishing a relatable protagonist who must overcome systemic friction to achieve self-actualization. Audiences have grown increasingly cynical toward sanitized, overwhelmingly positive portrayals of success, demanding instead a raw, unfiltered examination of the obstacles that precede any meaningful triumph. Consequently, the most persuasive communicators are those who strategically leverage their own failures and miscalculations to establish an unshakeable bedrock of credibility with their listeners. This paradoxical phenomenon—where admitting vulnerability actually maximizes persuasive authority—is the defining characteristic of contemporary rhetorical mastery.",
  "The accelerating proliferation of decentralized financial technologies poses a formidable challenge to traditional regulatory frameworks, compelling international banking consortiums to fundamentally restructure their operational paradigms. As cryptographic assets and blockchain ledgers bypass established institutional intermediaries, governmental authorities are struggling to implement cohesive taxation and compliance protocols without stifling technological innovation. Furthermore, the inherent volatility of these unregulated digital markets presents a significant systemic risk to the stability of the broader macro-economy. Consequently, financial architects must rapidly devise hybrid models that seamlessly integrate the efficiency of decentralized networks with the robust consumer protections demanded by conventional monetary policy.",
  "Geopolitical stability in the twenty-first century is increasingly dependent on securing resilient supply chains for critical semiconductor components, rather than solely relying on conventional military deterrence. The disproportionate concentration of microchip manufacturing within a handful of geopolitically sensitive regions has created a precarious bottleneck that threatens the continuous advancement of global technological infrastructure. In response, sovereign nations are aggressively deploying unprecedented domestic subsidies to repatriate advanced manufacturing capabilities and mitigate their reliance on foreign adversaries. This strategic pivot represents a monumental shift in international relations, where economic self-sufficiency is now universally recognized as the ultimate guarantor of national security.",
  "Rigorous academic methodologies demand that researchers rigorously isolate confounding variables, ensuring that empirical conclusions withstand the intense scrutiny of double-blind peer review and reproducible experimentation. The proliferation of predatory journals and the widespread misuse of statistical significance testing have unfortunately cast a shadow of doubt over the overarching credibility of contemporary scientific literature. To restore public faith in academic institutions, researchers must commit to absolute transparency regarding their datasets, funding sources, and potential conflicts of interest. Only by cultivating a culture of unwavering intellectual honesty can the scientific community continue to act as the definitive arbiter of empirical truth in an increasingly skeptical society."
];

async function main() {
  const { rows } = await pool.query("SELECT id, difficulty FROM exercises WHERE difficulty IN ('medium', 'hard') ORDER BY id ASC");
  
  let mediumIdx = 0;
  let hardIdx = 0;

  for (const row of rows) {
    let newContent = '';
    if (row.difficulty === 'medium') {
      newContent = mediumParagraphs[mediumIdx % mediumParagraphs.length];
      mediumIdx++;
    } else {
      newContent = hardParagraphs[hardIdx % hardParagraphs.length];
      hardIdx++;
    }

    await pool.query("UPDATE exercises SET text_content = $1 WHERE id = $2", [newContent, row.id]);
  }
  
  console.log(`Updated ${rows.length} exercises directly in the DB!`);
  pool.end();
}

main();