const fs = require('fs');
const path = require('path');

const domains = {
  domain1: {
    categories: ['conversation', 'storytelling', 'emotions', 'daily', 'interview'],
    medium: [
      { t: "Genuine Dialogue", c: "When we engage in genuine dialogue, we open ourselves up to new perspectives that challenge our preconceptions. True communication is not about winning an argument, but about expanding our understanding of the human experience. By actively listening and asking thoughtful questions, we create a safe space for others to share their vulnerabilities without fear of judgment." },
      { t: "Art of Storytelling", c: "Mastering the art of storytelling allows you to translate complex emotions into relatable experiences. A well-told narrative can capture the imagination, bridging the gap between strangers and fostering profound empathy. It requires a delicate balance of pacing, descriptive language, and an intuitive sense of what will resonate most deeply with your audience." },
      { t: "Tone and Pacing", c: "During an interview or formal discussion, your tone and pacing carry as much weight as your actual words. Taking a moment to breathe and center yourself before speaking projects quiet confidence and professional authority. Furthermore, adjusting your volume to match the gravity of the topic ensures that your message is received exactly as intended." },
      { t: "Everyday Interactions", c: "Our daily interactions may seem routine, but they form the invisible fabric of our social lives. Approaching everyday conversations with kindness and presence can transform a mundane exchange into a moment of genuine connection. Recognizing the value in these small, seemingly insignificant encounters often leads to a more fulfilling and grounded sense of community." },
      { t: "Expressing Emotions", c: "Expressing difficult emotions requires both courage and a precise vocabulary. When we accurately articulate how we feel, we give others the opportunity to support us effectively, turning personal struggle into shared strength. This process not only accelerates our own healing but also deepens the trust and intimacy within our most important relationships." },
      { t: "Calm Under Pressure", c: "The ability to remain calm and articulate under pressure is a hallmark of emotional maturity. When conflicts arise, responding with measured, empathetic words can de-escalate the situation and pave the way for meaningful resolution. It demands a high level of self-awareness to pause your initial reaction and choose a constructive path forward." },
      { t: "Active Listening", c: "Active listening is a dynamic process that involves fully concentrating on what is being said rather than passively hearing the message. It is the fundamental building block of any successful personal or professional relationship. Providing verbal and non-verbal feedback demonstrates that you genuinely value the speaker's time, insights, and underlying emotions." },
      { t: "Finding Your Voice", c: "Finding your authentic voice takes time, patience, and a willingness to engage in deep self-reflection. As you grow more comfortable with your own communication style, you will discover that people are naturally drawn to sincerity and unwavering honesty. It is an ongoing journey of discovering who you are and learning how to express that truth without apology." },
      { t: "Compelling Narratives", c: "A compelling narrative doesn't just relay facts; it weaves them together in a way that resonates emotionally with the audience. Cultivating this skill empowers you to advocate for yourself and inspire those around you to take meaningful action. Whether in a boardroom or at a dinner table, a well-structured story is the most effective tool for lasting persuasion." }
    ],
    hard: [
      { t: "Psychology of Breakthroughs", c: "The intricacies of human psychology dictate that our most profound personal breakthroughs often emerge from periods of intense vulnerability and emotional uncertainty, challenging us to reevaluate our core identity. When individuals are forced to confront their deeply ingrained defense mechanisms, they often discover an untapped reservoir of resilience that fundamentally alters their worldview. Furthermore, the capacity to articulate these internal paradigm shifts requires an extraordinarily sophisticated emotional vocabulary. Only by meticulously deconstructing our past traumas can we begin to construct a more authentic and purposeful framework for our future interpersonal relationships." },
      { t: "High-Stakes Interviews", c: "During high-stakes professional interviews, the candidate who successfully balances authentic self-representation with strategic corporate alignment consistently outperforms those who rely solely on rehearsed, formulaic responses. Evaluators at the executive level are trained to detect nuanced micro-expressions that betray cognitive dissonance or a lack of genuine conviction. Consequently, mastering this high-pressure environment demands rigorous psychological preparation and an unwavering commitment to transparent communication. The ultimate goal is to seamlessly weave your unique professional narrative into the broader, overarching vision of the organization you are seeking to join." },
      { t: "Evolutionary Storytelling", c: "Storytelling transcends mere entertainment; it is an evolutionary survival mechanism that enables communities to encode complex moral lessons, preserve generational wisdom, and foster cohesive social architectures. Throughout human history, tribes that developed sophisticated oral traditions were demonstrably more successful at navigating environmental catastrophes and coordinating large-scale collective action. Today, this ancient biological imperative manifests in our insatiable appetite for cinema, literature, and digital media. Understanding the structural mechanics of these archetypal narratives is essential for anyone attempting to capture the fragmented attention of the modern public." },
      { t: "Interpersonal Subtleties", c: "Mastering the subtleties of interpersonal communication requires an acute awareness of non-verbal cues, microscopic shifts in tone, and the underlying contextual dynamics that govern every human interaction. Frequently, the most critical information in a dialogue is not explicitly stated, but rather conveyed through deliberate silences, subtle hesitations, and fleeting facial expressions. Developing the emotional intelligence required to accurately decipher these covert signals is a lifelong endeavor that yields immeasurable dividends in both our private lives and professional careers. Ultimately, it is the unspoken subtext that dictates the true trajectory of our most significant negotiations." },
      { t: "Dismantling Cognitive Dissonance", c: "When we actively dismantle the cognitive dissonance separating our private emotional state from our outward expressions, we cultivate a profound sense of inner peace and relational authenticity. This rigorous introspective process requires us to critically examine the societal conditioning that encourages us to suppress our most authentic, albeit inconvenient, emotional reactions. By systematically rejecting these superficial behavioral paradigms, we invite a level of psychological vulnerability that is inherently terrifying yet absolutely necessary for genuine human connection. The courage required to live transparently is perhaps the rarest and most admirable of all modern virtues." },
      { t: "Compounding Daily Routines", c: "The daily routines we establish may seem insignificant in isolation, but compounded over decades, they dictate the ultimate trajectory of our professional achievements and the depth of our personal fulfillment. Neuroscientific research consistently demonstrates that habitual behaviors literally rewire the synaptic pathways of the brain, making proactive, disciplined choices increasingly automated over time. Conversely, allowing negative communication patterns to take root guarantees a gradual erosion of trust and mutual respect within our closest relationships. Therefore, cultivating a deliberate and mindful approach to our daily interactions is the most pragmatic strategy for ensuring long-term emotional well-being." },
      { t: "Precise Emotional Vocabulary", c: "Articulating complex emotional states with precise vocabulary not only accelerates psychological healing but also provides our support networks with the clarity required to offer meaningful, targeted assistance. Unfortunately, the modern vernacular frequently relies on vague, generalized descriptors that fail to capture the nuanced realities of the human condition, leaving individuals feeling fundamentally misunderstood. By expanding our emotional lexicon, we empower ourselves to navigate the labyrinthine complexities of grief, joy, and existential anxiety with unprecedented grace. This linguistic precision acts as a crucial bridge, allowing empathy to traverse the otherwise insurmountable gulf between isolated subjective experiences." },
      { t: "Navigating Disagreements", c: "Navigating ideological disagreements gracefully demands that we temporarily suspend our deeply ingrained defensive reflexes in favor of genuine intellectual curiosity and empathetic active listening. In an era characterized by hyper-partisan polarization, the willingness to entertain conflicting viewpoints without immediately resorting to ad hominem attacks is an increasingly scarce commodity. True intellectual courage involves systematically interrogating the foundational premises of our own arguments while actively seeking the strongest possible interpretation of our opponent's position. This methodology, often referred to as steel-manning, is the only reliable mechanism for breaking through the echo chambers that currently paralyze constructive public discourse." },
      { t: "Modern Narrative Arc", c: "The modern narrative arc, whether deployed in corporate branding or personal memoirs, relies heavily on establishing a relatable protagonist who must overcome systemic friction to achieve self-actualization. Audiences have grown increasingly cynical toward sanitized, overwhelmingly positive portrayals of success, demanding instead a raw, unfiltered examination of the obstacles that precede any meaningful triumph. Consequently, the most persuasive communicators are those who strategically leverage their own failures and miscalculations to establish an unshakeable bedrock of credibility with their listeners. This paradoxical phenomenon—where admitting vulnerability actually maximizes persuasive authority—is the defining characteristic of contemporary rhetorical mastery." }
    ]
  },
  domain2: {
    categories: ['business', 'news', 'academic', 'politics', 'geopolitics', 'technology', 'diplomatic', 'formal'],
    medium: [
      { t: "AI Integration", c: "The rapid integration of artificial intelligence into enterprise operations demands a fundamental shift in how we approach problem-solving. Organizations that proactively adapt their strategies will maintain a crucial competitive advantage in the modern economy. Employees must be trained to collaborate alongside these algorithms, utilizing their unprecedented data-processing capabilities to drive innovation." },
      { t: "Navigating Geopolitics", c: "Navigating geopolitical tensions requires a nuanced understanding of historical grievances and current economic dependencies. Diplomats must meticulously choose their words to de-escalate conflicts while firmly protecting their national interests. A single misinterpretation of intent can rapidly unravel months of delicate negotiations, underscoring the absolute necessity for precision in international discourse." },
      { t: "Peer Review Process", c: "In the realm of academic research, the peer review process serves as a vital safeguard for maintaining factual accuracy. Scholars depend on constructive criticism to refine their hypotheses and contribute meaningful discoveries to their respective fields. By subjecting empirical data to rigorous, independent scrutiny, the scientific community collectively ensures the integrity of its expanding knowledge base." },
      { t: "Responsible Journalism", c: "Modern journalism faces the unprecedented challenge of combating misinformation in real time across decentralized digital platforms. Responsible reporting demands rigorous fact-checking and an unwavering commitment to presenting objective truth to the public. Journalists must consistently prioritize verified sources over sensationalized rumors to maintain the vital trust of an increasingly skeptical audience." },
      { t: "Corporate ESG", c: "Corporate leadership is increasingly focused on environmental, social, and governance criteria as a primary driver of valuation. Investors recognize that companies demonstrating ethical practices and sustainable operations are better positioned for long-term financial stability. Implementing these rigorous standards not only mitigates regulatory risks but also attracts top-tier talent seeking purposeful employment." },
      { t: "Formal Negotiation", c: "The language of formal negotiation is inherently strategic, often relying on subtle implications rather than blunt demands. Mastering this sophisticated communication style is essential for finalizing complex international agreements. Negotiators must expertly read the room, balancing aggressive tactical maneuvering with a genuine willingness to seek mutually beneficial compromises." },
      { t: "Technological Breakthroughs", c: "Technological breakthroughs rarely happen in isolation; they are the result of cumulative scientific progress and cross-disciplinary collaboration. Fostering an environment that encourages intellectual risk-taking is vital for continuous innovation. When engineers, designers, and scientists share their distinct methodologies, they consistently unlock solutions that would have remained invisible within isolated silos." },
      { t: "Public Policy Decisions", c: "Public policy decisions must carefully weigh empirical data against the immediate, tangible needs of the local community. Effective political leaders excel at translating complex legislative frameworks into clear, actionable benefits for their constituents. Transparent communication regarding how these policies will directly impact daily life is essential for maintaining democratic legitimacy and public support." },
      { t: "Supply Chain Resilience", c: "In today's globalized economy, supply chain resilience is a critical factor for long-term business survival. Companies must anticipate potential disruptions and build flexible networks to ensure the consistent delivery of goods and services. Diversifying manufacturing hubs and investing in predictive analytics allows organizations to pivot rapidly when unforeseen geopolitical or environmental crises inevitably occur." }
    ],
    hard: [
      { t: "Decentralized Finance", c: "The accelerating proliferation of decentralized financial technologies poses a formidable challenge to traditional regulatory frameworks, compelling international banking consortiums to fundamentally restructure their operational paradigms. As cryptographic assets and blockchain ledgers bypass established institutional intermediaries, governmental authorities are struggling to implement cohesive taxation and compliance protocols without stifling technological innovation. Furthermore, the inherent volatility of these unregulated digital markets presents a significant systemic risk to the stability of the broader macro-economy. Consequently, financial architects must rapidly devise hybrid models that seamlessly integrate the efficiency of decentralized networks with the robust consumer protections demanded by conventional monetary policy." },
      { t: "Geopolitical Supply", c: "Geopolitical stability in the twenty-first century is increasingly dependent on securing resilient supply chains for critical semiconductor components, rather than solely relying on conventional military deterrence. The disproportionate concentration of microchip manufacturing within a handful of geopolitically sensitive regions has created a precarious bottleneck that threatens the continuous advancement of global technological infrastructure. In response, sovereign nations are aggressively deploying unprecedented domestic subsidies to repatriate advanced manufacturing capabilities and mitigate their reliance on foreign adversaries. This strategic pivot represents a monumental shift in international relations, where economic self-sufficiency is now universally recognized as the ultimate guarantor of national security." },
      { t: "Academic Methodologies", c: "Rigorous academic methodologies demand that researchers rigorously isolate confounding variables, ensuring that empirical conclusions withstand the intense scrutiny of double-blind peer review and reproducible experimentation. The proliferation of predatory journals and the widespread misuse of statistical significance testing have unfortunately cast a shadow of doubt over the overarching credibility of contemporary scientific literature. To restore public faith in academic institutions, researchers must commit to absolute transparency regarding their datasets, funding sources, and potential conflicts of interest. Only by cultivating a culture of unwavering intellectual honesty can the scientific community continue to act as the definitive arbiter of empirical truth in an increasingly skeptical society." },
      { t: "Corporate Sustainability", c: "Corporate sustainability initiatives must evolve beyond superficial marketing campaigns and integrate deeply into the core logistical infrastructure, prioritizing long-term ecological balance over immediate quarterly dividends. For decades, multinational conglomerates have externalized the devastating environmental costs of their manufacturing processes, transferring the burden of ecological remediation onto marginalized local communities. However, the escalating frequency of climate-driven supply chain disruptions is finally forcing executive boards to recognize that environmental stewardship and fiduciary responsibility are no longer mutually exclusive concepts. Implementing fully circular economic models is not merely an ethical imperative; it is an absolute prerequisite for ensuring the ongoing viability of global capitalism." },
      { t: "Diplomatic Resolution", c: "The diplomatic resolution of entrenched territorial disputes requires negotiators to architect innovative treaties that allow all participating factions to claim ideological victory while making substantial pragmatic concessions. Historic animosities, often spanning several centuries and heavily reinforced by nationalist propaganda, create a highly volatile atmosphere where even minor linguistic ambiguities can instantly derail the peace process. Experienced diplomats must utilize a highly specialized, nuanced vocabulary that acknowledges past grievances without validating inflammatory rhetoric or conceding critical strategic advantages. Achieving a lasting consensus in these high-stakes environments is arguably the most intellectually demanding and psychologically exhausting endeavor within the realm of international relations." },
      { t: "Ethical AI Constraints", c: "As artificial intelligence algorithms become increasingly autonomous, the technology sector faces an urgent philosophical imperative to encode ethical constraints that prevent the exacerbation of historical socioeconomic biases. Machine learning models fundamentally rely on vast troves of historical data, which inherently contain the prejudiced assumptions and discriminatory practices of the societies that generated them. If deployed without rigorous algorithmic auditing, these predictive systems will undoubtedly automate and scale systemic inequalities, particularly within critical sectors such as criminal justice, healthcare allocation, and corporate recruitment. Establishing a universal, standardized framework for algorithmic accountability is the defining moral challenge of the contemporary technological era." },
      { t: "Political Governance", c: "Effective political governance necessitates the delicate orchestration of competing bureaucratic interests, requiring leaders to synthesize highly technical policy recommendations into cohesive, actionable legislative agendas. In heavily polarized democratic systems, the mechanics of passing substantive legislation frequently involve navigating a labyrinth of procedural gridlock, partisan grandstanding, and relentless lobbying by well-funded special interest groups. Successful politicians must possess an extraordinary capacity for pragmatic compromise, expertly identifying the microscopic areas of overlapping consensus that exist between fiercely opposed ideological factions. Without this sophisticated capacity for coalition-building, governments are inevitably paralyzed by perpetual dysfunction and administrative stagnation." },
      { t: "Journalistic Integrity", c: "The integrity of global journalism is currently under siege by highly sophisticated disinformation campaigns, rendering the verification of primary sources and the contextualization of digital media more critical than ever. State-sponsored actors and decentralized extremist networks frequently utilize deep-fake technology and coordinated bot swarms to manufacture artificial outrage, systematically eroding the public's foundational trust in traditional democratic institutions. To effectively combat this unprecedented epistemological crisis, news organizations must heavily invest in advanced forensic analysis while simultaneously increasing the transparency of their internal editorial processes. The survival of an informed electorate depends entirely upon the press's ability to consistently differentiate empirical reality from weaponized, algorithmic propaganda." },
      { t: "Corporate Communications", c: "Formal corporate communications must strike a precarious balance between absolute transparency and strategic confidentiality, particularly when addressing hostile shareholders during periods of unanticipated market volatility. During a severe public relations crisis, the speed and tonality of an organization's initial response will almost entirely dictate the subsequent trajectory of their brand equity and market capitalization. Executives must forcefully articulate a comprehensive remediation strategy without inadvertently exposing the corporation to debilitating class-action litigation or regulatory sanctions. This incredibly intricate high-wire act requires a masterful command of legal phrasing, empathetic messaging, and uncompromising operational authority." }
    ]
  },
  domain3: {
    categories: ['travel', 'tongue_twisters', 'classic_literature', 'speech', 'sports', 'diagnostic', 'ielts'],
    medium: [
      { t: "Immersive Travel", c: "The immersive experience of traveling through unfamiliar landscapes forces us to adapt and communicate in creative ways. These journeys not only expose us to incredible diversity but also reveal the fundamental similarities that connect all people. Breaking out of our comfort zones and engaging with foreign cultures fosters a deep, enduring sense of global empathy that cannot be learned from textbooks alone." },
      { t: "Vocal Mastery", c: "Mastering complex vocal exercises and tongue twisters develops the muscular memory required for flawless articulation. This rigorous phonetic practice directly translates to more confident and authoritative public speaking in any scenario. Consistent repetition strengthens the diaphragm and refines the precise movements of the tongue and lips, eliminating subtle stumbles that often undermine a speaker's credibility." },
      { t: "Athletic Endurance", c: "The endurance required in competitive sports is as much psychological as it is physical. Athletes who train their minds to overcome fatigue and self-doubt often find that this resilience empowers them in their personal and professional lives. The capacity to push past the body's perceived limitations reveals a hidden reservoir of willpower that is essential for achieving any truly ambitious goal." },
      { t: "Keynote Delivery", c: "When delivering a keynote address, the speaker must carefully orchestrate their vocal inflection and body language. A truly captivating speech harmonizes these physical elements with a deeply inspiring message that resonates with the audience. By strategically utilizing deliberate pauses, an orator allows the most impactful statements to settle into the minds of the listeners, maximizing their emotional effect." },
      { t: "Studying Classics", c: "Studying classic literature exposes us to the evolution of language and the enduring nature of human conflict. By analyzing the prose of great authors, we refine our own ability to construct elegant, persuasive arguments. Engaging with these historical texts provides invaluable context for contemporary societal issues, demonstrating that our modern struggles are merely new iterations of ancient philosophical dilemmas." },
      { t: "Diagnostic Assessment", c: "Diagnostic language assessments are designed to identify specific phonetic weaknesses and structural knowledge gaps. By objectively measuring these metrics, learners can create highly targeted study plans that dramatically accelerate their path to fluency. This analytical approach eliminates the frustration of unstructured learning, ensuring that every hour of practice yields a measurable, concrete improvement in conversational ability." },
      { t: "Exam Proficiency", c: "Achieving a high band score in international proficiency exams requires more than just a wide vocabulary. Candidates must demonstrate the ability to construct logically coherent arguments, use complex grammatical structures, and speak with natural fluency. Evaluators are specifically trained to look for seamless transitions between ideas, assessing whether the speaker can articulate abstract concepts without relying on memorized templates." },
      { t: "Well-Crafted Sentences", c: "The beauty of a well-crafted sentence lies in its rhythm and economy of words. Great orators understand that pausing for emphasis is just as crucial as the words themselves, allowing the audience time to absorb the full weight of the message. Eliminating unnecessary filler words clarifies the core argument, ensuring that the listener's attention remains entirely focused on the speaker's primary objective." },
      { t: "Cultural Immersion", c: "Cultural immersion is the ultimate test of language acquisition. Navigating foreign environments without the safety net of translation forces the brain to rapidly internalize new linguistic patterns and contextual social cues. This sink-or-swim methodology is remarkably effective, as it inextricably links vocabulary retention to the immediate, visceral necessity of daily survival and social integration." }
    ],
    hard: [
      { t: "Cultural Immersion", c: "Immersive international travel systematically dismantles ethnocentric prejudices by forcing individuals to navigate unfamiliar linguistic environments, ultimately fostering a more nuanced appreciation for global cultural heterogeneity. When travelers are completely divorced from their native support systems, they must rely on intense observational skills and non-verbal communication to decode complex, unwritten social contracts. This disorienting process of continuous adaptation fundamentally rewires the traveler's cognitive framework, replacing superficial stereotypes with a profound, firsthand understanding of shared human universalities. Ultimately, extensive cultural immersion serves as the most potent antidote to the insidious rise of xenophobia and isolationist political ideologies." },
      { t: "Physiological Articulation", c: "The physiological mechanics of advanced vocal articulation require the synchronized execution of the diaphragm, larynx, and articulatory muscles, a process that is significantly enhanced through repetitive phonetic conditioning. Professional vocalists and stage actors dedicate thousands of hours to these grueling exercises, ensuring that their projection remains uncompromised even during extended performances in acoustically hostile environments. Furthermore, maintaining optimal breath control fundamentally mitigates the physiological symptoms of performance anxiety, allowing the speaker's central nervous system to remain regulated under intense public scrutiny. This biomechanical mastery transforms the human voice into an incredibly precise instrument, capable of conveying microscopic variations in emotional subtext." },
      { t: "Classical Archetypes", c: "Scholarly analysis of classical literature reveals that the fundamental archetypes of human conflict remain remarkably consistent across millennia, despite drastic shifts in technological advancement and societal organization. By meticulously dissecting the syntactic structures and thematic motifs employed by historical literary giants, modern readers gain invaluable insight into the enduring fragility of human ambition and the cyclical nature of political hubris. These ancient narratives serve as a profound psychological mirror, forcing us to confront the uncomfortable reality that our contemporary existential anxieties are practically indistinguishable from those documented during antiquity. Consequently, classical literature remains an indispensable pedagogical tool for cultivating profound historical empathy." },
      { t: "Oratorical Performance", c: "Delivering a truly compelling oratorical performance necessitates the strategic manipulation of rhetorical devices, utilizing deliberate pauses and dynamic vocal projection to capture and sustain the audience's undivided attention. The most historically consequential speeches share a distinct architectural blueprint: they simultaneously validate the audience's immediate grievances while vividly painting an aspirational portrait of a radically improved future. Achieving this delicate rhetorical equilibrium requires an encyclopedic command of vocabulary, impeccable comedic timing, and an almost preternatural ability to read and respond to the fluctuating energy of a live crowd. True oratorical genius is an incredibly rare synthesis of meticulous psychological preparation and spontaneous, improvisational brilliance." },
      { t: "Athletic Optimization", c: "Elite athletic performance at the championship level is characterized not merely by genetic predisposition, but by the relentless, methodical optimization of biomechanics, nutritional chemistry, and psychological resilience. In an era where the margins of victory are frequently measured in fractions of a millisecond, sports scientists utilize highly advanced biometric sensors to identify and eliminate microscopic inefficiencies within an athlete's kinetic chain. Simultaneously, sports psychologists implement rigorous cognitive behavioral therapies to inoculate competitors against the paralyzing effects of catastrophic pressure during critical, high-stakes scenarios. This holistic, data-driven approach to human performance has completely redefined the theoretical limitations of physiological capability." },
      { t: "Linguistic Diagnostics", c: "Comprehensive linguistic diagnostic assessments evaluate a multitude of intricate variables, including phonemic accuracy, syntactic complexity, and prosodic intonation, to construct a highly personalized pedagogical intervention. Advanced algorithmic software can now analyze audio waveforms in real-time, detecting imperceptible mispronunciations and regional dialectical interference with a level of precision that far exceeds human auditory capabilities. By aggressively targeting these specific articulatory deficiencies through customized phonetic drills, adult language learners can successfully bypass the deeply ingrained neurological barriers that typically prevent the acquisition of a native-sounding accent. This technological revolution has democratized access to elite-level pronunciation coaching, previously reserved exclusively for professional diplomats and intelligence operatives." },
      { t: "Language Proficiency", c: "To secure the highest possible evaluation in standardized language proficiency examinations, candidates must seamlessly deploy advanced lexical resources while maintaining an uncompromised flow of coherent, logical argumentation. Examiners are specifically trained to ruthlessly penalize structural redundancy, hesitation markers, and the over-reliance on memorized, formulaic transition phrases. A genuinely superior performance requires the candidate to effortlessly pivot between abstract philosophical debates and hyper-specific technical jargon, demonstrating a highly flexible, encyclopedic command of the target language. Ultimately, achieving total mastery requires the complete internalization of the language's unique idiomatic rhythm, completely bypassing the cognitive delay associated with internal translation." },
      { t: "Neurological Speech", c: "The deliberate practice of complex tongue twisters forces the neurological pathways governing speech production to adapt rapidly, thereby eliminating habitual mispronunciations and significantly elevating overall conversational fluency. This aggressive phonetic conditioning deliberately overwhelms the articulatory cortex, exposing structural weaknesses in the speaker's pronunciation that are easily masked during slower, more casual discourse. As the brain continuously repairs and optimizes these over-taxed neural circuits, the individual develops a vastly superior level of muscular coordination across the entire vocal apparatus. This rigorous methodology is universally prescribed by elite speech pathologists to rectify persistent stammers and instill an aura of unshakeable verbal authority." },
      { t: "Societal Transformations", c: "Historical speeches that have catalyzed significant societal transformations are invariably characterized by their ability to crystallize abstract philosophical ideals into visceral, emotionally resonant imperatives for immediate action. Visionary leaders possess an intuitive understanding of the collective psychological zeitgeist, allowing them to weaponize rhetoric in a manner that completely short-circuits the public's inherent resistance to radical systemic change. By framing complex political objectives as undeniable moral imperatives, these orators can successfully mobilize millions of disparate individuals to sacrifice their short-term comfort for the promise of a utopian future. Studying the underlying mechanics of these paradigm-shifting addresses is absolutely essential for understanding the historical mechanics of non-violent political revolution." }
    ]
  }
};

let sql = `-- Migration 018: Lengthen content for Medium and Hard exercises to ensure they have substantial depth and reading time.
-- This updates the exercises modified in Migration 017 to longer texts.

`;

const difficulties = ['medium', 'hard'];

for (const [domainName, domainData] of Object.entries(domains)) {
  for (const category of domainData.categories) {
    for (const diff of difficulties) {
      const items = domainData[diff];
      for (let i = 0; i < 9; i++) {
        const item = items[i];
        // Ensure no quotes break the SQL
        const safeContent = item.c.replace(/'/g, "''");
        
        sql += `
WITH target AS (
  SELECT id FROM exercises 
  WHERE category = '${category}' 
    AND difficulty = '${diff}' 
  ORDER BY id ASC
  OFFSET ${i} LIMIT 1
)
UPDATE exercises
SET text_content = '${safeContent}'
WHERE id = (SELECT id FROM target);
`;
      }
    }
  }
}

const outPath = path.join(__dirname, 'src', 'migrations', '018_lengthen_content.sql');
fs.writeFileSync(outPath, sql);
console.log(`Generated migration 018 to lengthen Medium and Hard exercise text content`);
