CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "public_id" uuid UNIQUE NOT NULL,
  "firebase_uid" varchar UNIQUE NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "native_language" varchar,
  "target_accent" varchar,
  "created_at" timestamp DEFAULT (now())
);

CREATE INDEX ON "users" ("public_id");
CREATE INDEX ON "users" ("firebase_uid");
CREATE INDEX ON "users" ("email");
