CREATE TABLE "exercises" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "public_id" uuid UNIQUE NOT NULL,
  "title" varchar,
  "category" varchar,
  "text_content" text NOT NULL,
  "difficulty" varchar,
  "created_at" timestamp DEFAULT (now())
);

CREATE INDEX ON "exercises" ("public_id");
CREATE INDEX ON "exercises" ("category");
