CREATE TABLE "sessions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "public_id" uuid UNIQUE NOT NULL,
  "user_id" bigint NOT NULL,
  "exercise_id" bigint NOT NULL,
  "status" varchar NOT NULL DEFAULT 'pending',
  "overall_accuracy" numeric(5,2),
  "fluency_score" numeric(5,2),
  "duration_seconds" integer,
  "created_at" timestamp DEFAULT (now())
);

CREATE INDEX ON "sessions" ("public_id");
CREATE INDEX ON "sessions" ("user_id");
CREATE INDEX ON "sessions" ("exercise_id");
CREATE INDEX ON "sessions" ("created_at");
CREATE INDEX ON "sessions" ("user_id", "created_at");

ALTER TABLE "sessions"
  ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sessions"
  ADD FOREIGN KEY ("exercise_id") REFERENCES "exercises" ("id") DEFERRABLE INITIALLY IMMEDIATE;
