CREATE TABLE "subscriptions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "public_id" uuid UNIQUE NOT NULL,
  "user_id" bigint NOT NULL,
  "plan_type" varchar,
  "status" varchar,
  "started_at" timestamp,
  "expires_at" timestamp,
  "created_at" timestamp DEFAULT (now())
);

CREATE INDEX ON "subscriptions" ("public_id");
CREATE INDEX ON "subscriptions" ("user_id");
CREATE INDEX ON "subscriptions" ("status");

ALTER TABLE "subscriptions"
  ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
