CREATE TABLE "usage_tracking" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "usage_date" date NOT NULL,
  "minutes_used" integer DEFAULT 0,
  "sessions_count" integer DEFAULT 0,
  "created_at" timestamp DEFAULT (now())
);

CREATE INDEX ON "usage_tracking" ("user_id");
CREATE INDEX ON "usage_tracking" ("usage_date");
CREATE INDEX ON "usage_tracking" ("user_id", "usage_date");

ALTER TABLE "usage_tracking"
  ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

-- Ensure one row per user per day
ALTER TABLE "usage_tracking"
  ADD CONSTRAINT usage_tracking_user_date_unique UNIQUE ("user_id", "usage_date");
