CREATE TABLE "plans" (
  "id"             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name"           varchar UNIQUE NOT NULL,
  "display_name"   varchar NOT NULL,
  "daily_sessions" integer NOT NULL,
  "created_at"     timestamp DEFAULT (now())
);

CREATE INDEX ON "plans" ("name");

INSERT INTO "plans" ("name", "display_name", "daily_sessions")
VALUES
  ('free', 'Free', 3),
  ('pro',  'Pro',  999);
